import { pathToFileURL } from "node:url";

function parsedBody(text) {
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

/// Classifies the post-deploy polish probe without confusing OpenAI/edge health with
/// artifact health. `rollback` is reserved for evidence that the deployed client
/// contract itself is wrong; an upstream or transport failure is `inconclusive`.
export function classifyRelaySmoke(statusText, bodyText) {
  if (!/^\d{3}$/.test(statusText || "") || statusText === "000") {
    return { verdict: "inconclusive", reason: "transport" };
  }

  const status = Number(statusText);
  const body = parsedBody(bodyText);
  if (status === 200) {
    const content = body?.choices?.[0]?.message?.content;
    return typeof content === "string" && content.trim().length > 0
      ? { verdict: "pass", reason: "client-contract" }
      : { verdict: "rollback", reason: "invalid-200-body" };
  }

  // The probe URL is fixed by this release. Any 404 therefore proves that the public
  // route the client needs is absent, whether nginx/Cloudflare emitted HTML or the
  // relay emitted JSON. Normalise the reason so three identical statuses still count
  // as one repeated deterministic failure when their bodies differ.
  if (status === 404) return { verdict: "rollback", reason: "http-404" };

  const relayErrorCode = body?.error?.code;
  const deterministicRelayErrors = new Set([
    "relay_body_too_large",
    "relay_internal_error",
    "relay_invalid_json",
    "relay_invalid_request",
    "relay_not_found",
    "relay_unauthorized",
    "relay_upstream_authentication",
  ]);
  if (deterministicRelayErrors.has(relayErrorCode)) {
    return { verdict: "rollback", reason: relayErrorCode };
  }

  // These can all be produced by a healthy relay while OpenAI, the network, or the
  // edge is unavailable. Rolling source and dependencies back cannot repair them and
  // adds a second restart that disconnects every live dictation.
  if (status >= 500 || [408, 425, 429].includes(status)) {
    return { verdict: "inconclusive", reason: `upstream-or-edge-${status}` };
  }

  // OpenAI's structured 400 means the model/request assembled by this release is
  // invalid even though the relay accepted and forwarded it. A bare or HTML 400 can be
  // generated by an edge/WAF and is not enough evidence to roll working code back.
  const upstreamRequestCodes = new Set([
    "context_length_exceeded",
    "invalid_model",
    "invalid_request_error",
    "invalid_type",
    "invalid_value",
    "missing_required_parameter",
    "model_not_found",
    "unknown_parameter",
    "unsupported_model",
    "unsupported_value",
  ]);
  if (status === 400
      && (upstreamRequestCodes.has(relayErrorCode)
        || body?.error?.type === "invalid_request_error")) {
    return {
      verdict: "rollback",
      reason: relayErrorCode || "invalid_request_error",
    };
  }
  return { verdict: "inconclusive", reason: `edge-http-${status}` };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  let input = "";
  process.stdin.setEncoding("utf8");
  process.stdin.on("data", (chunk) => { input += chunk; });
  process.stdin.on("end", () => {
    const result = classifyRelaySmoke(process.argv[2] || "", input);
    process.stdout.write(`${result.verdict}\t${result.reason}\n`);
  });
}
